
spring:
  thymeleaf:
    cache: false
  h2:
    console:
      enabled: true
  data:
    rest:
      base-path: /api
  artemis:
    host: artemis.tacocloud.com
    port: 61617
    user: tacoweb
    password: l3tm31n
#  jms:
#    template:
#      default-destination: tacocloud.order.queue
taco:
  orders:
    page-size: 10