
spring:
  thymeleaf:
    cache: false
  h2:
    console:
      enabled: true
  data:
    rest:
      base-path: /api
  artemis:
    host: artemis.tacocloud.com
    port: 61617
    user: tacoweb
    password: l3tm31n
  profiles: prod
  rabbitmq:
    host: rabbit.tacocloud.com
    port: 5673
    username: tacoweb
    password: l3tm31n
    template:
      exchange: tacocloud.orders
      routing-key: kichens.central
  kafka:
    bootstrap-servers: -kafka.tacocloud.com:9092
    template:
      default-topic: tacocloud.orders.topic
#  jms:
#    template:
#      default-destination: tacocloud.order.queue
taco:
  orders:
    page-size: 10
tacocloud:
    email:
      host: imap.tacoclud.com
      mailbox: INBOx
      username: taco-in-flow
      passwod: 1L0v3T4c0s
      poll-rate: 10000
    api:
      url: http://api.tacoclud.com